// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['main']['MusicApp']['Close'](arg1);
}

export function Maximize(arg1) {
  return window['go']['main']['MusicApp']['Maximize'](arg1);
}

export function Minimize(arg1) {
  return window['go']['main']['MusicApp']['Minimize'](arg1);
}

export function Restore(arg1) {
  return window['go']['main']['MusicApp']['Restore'](arg1);
}
