// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptCENC(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function ExtractAudio(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FullPipeline(arg1:string,arg2:string,arg3:string):Promise<Array<number>>;

export function GetAudioBytes(arg1:string):Promise<Array<number>>;
