// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptCENC(arg1, arg2, arg3) {
  return window['go']['main']['MusicApp']['DecryptCENC'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['MusicApp']['DownloadFile'](arg1, arg2);
}

export function ExtractAudio(arg1, arg2, arg3) {
  return window['go']['main']['MusicApp']['ExtractAudio'](arg1, arg2, arg3);
}

export function FullPipeline(arg1, arg2, arg3) {
  return window['go']['main']['MusicApp']['FullPipeline'](arg1, arg2, arg3);
}

export function GetAudioBytes(arg1) {
  return window['go']['main']['MusicApp']['GetAudioBytes'](arg1);
}
