// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Close(arg1:context.Context):Promise<void>;

export function Maximize(arg1:context.Context):Promise<void>;

export function Minimize(arg1:context.Context):Promise<void>;

export function Restore(arg1:context.Context):Promise<void>;
